### ISSUE TITLE
Theme: Colors and Fonts

### ISSUE THREAD

**Issue by swiftcode** [devict/publicmeetings-front#1]
Design an initial look and feel.  We'll need a color scheme, fonts, graphics and logos.  Ideally, the theme will work on all platforms (Web, iOS, Android), though there may be some design differences.

**Comment by woodinteractive** [comment]
Colors, Styles, and Fonts are able to be referenced here: https://www.figma.com/file/QrVm7gvoF3U1FNVYOJqFmF/Public-Meetings-%E2%80%93-Front-end?node-id=0%3A1
